### PR TITLE
Support ESX_Weight

### PR DESCRIPTION
**Pull request by YuriZoko**
EN : Support ESX_Weight
FR : Support de poids

### CODE REVIEW

**Comment by ElPumpo** [comment]
No, use xPlayer.canSwapItem

**Comment by YuriZoko** [comment]
Can you help me  ?...

**Comment by ElPumpo** [comment]
see the source code on xPlayer

**Comment by YuriZoko** [comment]
`
if v.name ~= _U('delivery') and xPlayer.canSwapItem(???, 1, ???, 1) then`

Can you help me please..

**Pull request closed without merging**
